trigger:
- main

pool:
  name: My_todo_agent

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'my_service'   # ✅ tera actual service connection name
    scriptType: 'ps'                  # ✅ PowerShell use karo, bash mat karo
    scriptLocation: 'inlineScript'
    inlineScript: |
      Write-Host "Creating Resource Group..."
      az group create --name paddu --location eastus2
  displayName: 'Create Azure Resource Group'
